/* =========================================================
  Solvanta Learning
  Configuration Template (config.example.js)

  This is the TEMPLATE file. Do not edit this file.

  HOW TO USE:
  1. Open the file: assets/js/config.js
  2. Replace PASTE_APPS_SCRIPT_URL_HERE with your
     Google Apps Script Web App URL
  3. Save the file

  The live URL belongs in assets/js/config.js only.
  That file is what the website reads. This file is
  here so you can see the expected format.
  ========================================================= */

window.SOLVANTA_CONFIG = {

  /*
   * Your Google Apps Script Web App URL.
   * Example:
   * https://script.google.com/macros/s/AKfycbxXXXXXXXXXXXXXXX/exec
   *
   * Get this URL after deploying the Web App in Google Apps Script.
   * Do not add a trailing slash.
   */
  API_URL: "PASTE_APPS_SCRIPT_URL_HERE",

  /*
   * The name of your platform.
   * Used in dynamic elements on the page.
   */
  SITE_NAME: "Solvanta Learning",

  /*
   * Support email address.
   * Shown as a fallback when the contact system is not connected.
   */
  SUPPORT_EMAIL: "helpdesk@solvantaconsulting.com"

};
